export const ERROR = "ERROR";
export const SHOW_LOADING = "SHOW_LOADING";
export const HIDE_LOADING = "HIDE_LOADING";

//account reducers
export const CONNECT_WALLET = "CONNECT_WALLET";
export const DISCONNECT_WALLET = "DISCONNECT_WALLET";
export const CHANGE_ACCOUNT = "CHANGE_ACCOUNT";
export const SET_ACCOUNT = "SET_ACCOUNT";
export const RESET_ACCOUNT = "RESET_ACCOUNT";

export const LOAD_NETWORK_BALANCE = "LOAD_NETWORK_BALANCE";
export const LOAD_TOKEN_BALANCE = "LOAD_TOKEN_BALANCE";

// tokens reducers
export const LOAD_FROM_TOKEN = "LOAD_FROM_TOKEN";
export const LOAD_TO_TOKEN = "LOAD_TO_TOKEN";

export const LOAD_FROM_AMOUNT = "LOAD_FROM_AMOUNT";
export const LOAD_TO_AMOUNT = "LOAD_TO_AMOUNT";

export const SWAP_TOKEN_SELECTION = "SWAP_TOKEN_SELECTION";

export const CHANGE_NETWORK = "CHANGE_NETWORK";
