export const ERROR = "ERROR";
export const SHOW_LOADING = "SHOW_LOADING";
export const HIDE_LOADING = "HIDE_LOADING";

//account reducers
export const CONNECT_WALLET = "CONNECT_WALLET";
export const DISCONNECT_WALLET = "DISCONNECT_WALLET";
export const CHANGE_ACCOUNT = "CHANGE_ACCOUNT";
export const SET_ACCOUNT = "SET_ACCOUNT";
export const RESET_ACCOUNT = "RESET_ACCOUNT";
export const UPDATE_AUTH_STATE = "UPDATE_AUTH_STATE";
export const AUTH_ERROR = "AUTH_ERROR";
export const SET_USER_CHAIN = "SET_USER_CHAIN";

export const LOAD_NETWORK_BALANCE = "LOAD_NETWORK_BALANCE";
export const LOAD_TOKEN_BALANCE = "LOAD_TOKEN_BALANCE";

// tokens reducers
export const LOAD_FROM_TOKEN = "LOAD_FROM_TOKEN";
export const LOAD_TO_TOKEN = "LOAD_TO_TOKEN";

export const LOAD_FROM_AMOUNT = "LOAD_FROM_AMOUNT";
export const LOAD_TO_AMOUNT = "LOAD_TO_AMOUNT";

export const SWAP_TOKEN_SELECTION = "SWAP_TOKEN_SELECTION";
export const ADD_LIQUIDITY = "ADD_LIQUIDITY";
export const SET_TOKEN0_PRICE = "SET_TOKEN0_PRICE";
export const SET_TOKEN1_PRICE = "SET_TOKEN1_PRICE";
export const APPROVE_DEX = "APPROVE_DEX";
export const APPROVE_TOKEN = "APPROVE_TOKEN";
export const DISAPPROVE_TOKEN = "DISAPPROVE_TOKEN";

export const GET_POOL_SHARE = "GET_POOL_SHARE";
export const RESET_POOL_SHARE = "RESET_POOL_SHARE";

export const SHOW_DEX_LOADING = "SHOW_DEX_LOADING";
export const HIDE_DEX_LOADING = "HIDE_DEX_LOADING";

export const CHANGE_NETWORK = "CHANGE_NETWORK";

export const DEX_ERROR = "DEX_ERROR";
export const UPDATE_SETTINGS = "UPDATE_SETTINGS";

export const LOAD_TOKEN_LIST = "LOAD_TOKEN_LIST";
export const IMPORT_TOKEN = "IMPORT_TOKEN";

export const SET_LP_BALANCE = "SET_LP_BALANCE";
export const APPROVE_LP_TOKENS = "APPROVE_LP_TOKENS";

export const SET_POOL_RESERVES = "SET_POOL_RESERVES";

export const VERIFY_SLIPPAGE = "VERIFY_SLIPPAGE";

export const PRICE_UPDATE = "PRICE_UPDATE";

export const SET_TOKEN_ABI = "SET_TOKEN_ABI";
export const SET_PAIR_DATA = "SET_PAIR_DATA";
export const RESET_PAIR_DATA = "RESET_PAIR_DATA";

export const RESET_POOL_DATA = "RESET_POOL_DATA";

export const START_TRANSACTION = "START_TRANSACTION";
export const UPDATE_TRANSACTION_STATUS = "UPDATE_TRANSACTION_STATUS";

export const GET_TOKEN_O_IN = "GET_TOKEN_O_IN";
export const GET_TOKEN_1_OUT = "GET_TOKEN_1_OUT";

export const START_PRICE_LOADING = "START_PRICE_LOADING";
export const STOP_PRICE_LOADING = "STOP_PRICE_LOADING";

//farming types
export const APPROVE_LP_FARM = "APPROVE_LP_FARM";
export const SHOW_FARM_LOADING = "SHOW_FARM_LOADING";
export const HIDE_FARM_LOADING = "HIDE_FARM_LOADING";
export const STAKE_LP_TOKENS = "STAKE_LP_TOKENS";
export const GET_FARM_POOL = "GET_FARM_POOL";
export const UNSTAKE_LP_TOKENS = "UNSTAKE_LP_TOKENS";
export const HARVEST_REWARDS = "HARVEST_REWARDS";
export const GET_LP_BALANCE_FARM = "GET_LP_BALANCE_FARM";
